# Generated by Django 5.2.4 on 2025-08-31 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0002_category_book_alter_bookmember_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmember',
            name='role',
            field=models.CharField(choices=[('partner', 'Partner'), ('manager', 'Manager'), ('manager', 'Admin')], default='member', max_length=10),
        ),
    ]
