# Generated by Django 5.2.4 on 2025-08-31 11:25
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.contrib.auth.models import User

def set_bookmember_created_by(apps, schema_editor):
    BookMember = apps.get_model('cashbook', 'BookMember')
    Book = apps.get_model('cashbook', 'Book')
    for book_member in BookMember.objects.all():
        # Assign the book's creator as the default created_by for existing records
        book_member.created_by = book_member.book.created_by
        book_member.save()

class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0004_alter_bookmember_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmember',
            name='invited_at',
        ),
        migrations.AddField(
            model_name='bookmember',
            name='created_by',
            field=models.ForeignKey(help_text='User who added this member to the book', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_book_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(set_bookmember_created_by),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='BookMember',
    #         name='created_by',
    #         field=models.ForeignKey(
    #             on_delete=models.SET_NULL,
    #             to='auth.User',
    #         ),
    #     ),
    #     migrations.RunPython(set_bookmember_created_by),
    # ]